//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadMail
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEmail
    {
        public int Id { get; set; }
        public int UidMail { get; set; }
        public Nullable<System.DateTime> DateMail { get; set; }
        public string FromMail { get; set; }
        public string SubjectMail { get; set; }
        public string BodyMail { get; set; }
        public Nullable<int> NoAttachments { get; set; }
        public string FIlesName { get; set; }
        public Nullable<bool> IsLoad { get; set; }
    }
}
