//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadMail
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int Id { get; set; }
        public string IncidentID { get; set; }
        public string BriefDescription { get; set; }
        public string Priority { get; set; }
        public string Impact { get; set; }
        public string CauseCode { get; set; }
        public string Category { get; set; }
        public string TicketStatus { get; set; }
        public string OpenTime { get; set; }
        public string AssignUserID { get; set; }
        public string ResponsibleGroupName { get; set; }
        public string NotifyBy { get; set; }
        public string ContactUserID { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactLastName { get; set; }
        public string ContactEmail { get; set; }
        public string ResolveTime { get; set; }
        public string ResolveUserID { get; set; }
        public string ResolutionCode { get; set; }
        public string ResolutionDesc { get; set; }
        public string ResolveGroupName { get; set; }
        public string VSLABreached { get; set; }
        public string Location { get; set; }
        public string Subcustomer { get; set; }
    }
}
